[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    'forge-std/=lib/forge-std/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
]
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]
[invariant]
runs = 128
depth = 128
fail_on_revert = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
